# STIG Manager with proxy for https

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/csmig/dev/x509/certs/servers/neo-2.localdomain/cert.pem:/etc/nginx/cert.pem
      - /home/csmig/dev/x509/certs/servers/neo-2.localdomain/privkey.pem:/etc/nginx/privkey.pem
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
    - "443:443"
  keycloak:
    image: nuwcdivnpt/stig-manager-auth:latest
    environment:
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_RELATIVE_PATH=/kc
      # uncomment below to persist Keycloak data
      # - ./kc/h2:/opt/keycloak/data/h2
  stigman:
    # image: registry1.dso.mil/ironbank/opensource/stig-manager/stig-manager:1.5.13
    # image: nuwcdivnpt/stig-manager:latest
    image: stig-manager:latest
    environment:
      - STIGMAN_OIDC_PROVIDER=http://keycloak:8080/kc/realms/stigman
      - STIGMAN_CLIENT_OIDC_PROVIDER=https://neo-2.localdomain/kc/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=morpheus.localdomain
      - STIGMAN_DB_PORT=50001
      - STIGMAN_DB_USER=stigman
      - STIGMAN_DB_PASSWORD=stigman
    init: true
    