events {
  worker_connections  4096;  ## Default: 1024
}
pid        /var/cache/nginx/nginx.pid;
http {
    server {
        listen                      443 ssl;
        server_name                 neo-2.localdomain;
        root                        /usr/share/nginx/html;
        client_max_body_size        100M;      
        ssl_certificate             /etc/nginx/cert.pem;
        ssl_certificate_key         /etc/nginx/privkey.pem;
        ssl_prefer_server_ciphers   on;
                
        error_log                   /var/log/nginx/error.log debug;

        location / {
            autoindex on;
            ssi on;
        }
        location /stigman/ {
            proxy_pass              http://morpheus.localdomain:64001/;
            gzip on;
            gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
            gzip_min_length 256;
        }

        # # Disable proxy_buffering for collection cloning
        # # POST /stigman/api/collections/<collection-id>/clone
        # location ~ ^/stigman/api/collections/[^/]+/clone(?:\?.*)?$ {
        #     proxy_buffering         off;
        #     rewrite ^/stigman/(.*)$ /$1 break;
        #     proxy_pass              http://morpheus.localdomain:64001;
        # }

        # # Disable proxy_buffering for export-to collection
        # # POST /stigman/api/collections/<collection-id>/export-to/<anything>
        # location ~ ^/stigman/api/collections/[^/]+/export-to/[^/]+$ {
        #     proxy_buffering         off;
        #     rewrite ^/stigman/(.*)$ /$1 break;
        #     proxy_pass              http://morpheus.localdomain:64001;
        # }

        # # Disable proxy_buffering for SSE endpoint
        # location /stigman/api/op/state/sse {
        #     proxy_buffering         off;
        #     proxy_pass              http://morpheus.localdomain:64001/api/op/state/sse;
        # }
        
        # Enable WebSocket support for /log-socket
        location /stigman/log-socket {
            proxy_pass              http://morpheus.localdomain:64001/log-socket;
            proxy_http_version      1.1;
            proxy_set_header        Upgrade $http_upgrade;
            proxy_set_header        Connection "upgrade";
            proxy_set_header        Host $host;
            proxy_read_timeout      3600s;
        }

        location /kc/ {
            proxy_pass              http://keycloak:8080/kc/;
            proxy_set_header        Host               $host;
            proxy_set_header        X-Real-IP          $remote_addr;
            proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Host   $host;
            proxy_set_header        X-Forwarded-Server $host;
            proxy_set_header        X-Forwarded-Port   $server_port;
            proxy_set_header        X-Forwarded-Proto  $scheme;
            proxy_buffer_size       128k;
            proxy_buffers           4 256k;
            proxy_busy_buffers_size 256k;
        }

        location /auth/ {
            proxy_pass              http://morpheus.localdomain:8082/;
            proxy_set_header        Host               $host;
            proxy_set_header        X-Real-IP          $remote_addr;
            proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Host   $host;
            proxy_set_header        X-Forwarded-Server $host;
            proxy_set_header        X-Forwarded-Port   $server_port;
            proxy_set_header        X-Forwarded-Proto  $scheme;
        }
    }

}
